version: '3.8'

services:
  postgres:
    container_name: "snippet-permissions-db"
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
    volumes:
      - snippet_permissions_data:/var/lib/postgresql/data

  app:
    container_name: snippet-permissions
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres

volumes:
  snippet_permissions_data:
