name: CI

on:
  push:

  pull_request:
    branches:
      - dev
      - main


jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.PACKAGE_TOKEN }}
